CLOUDFLARE_ERROR = "CLOUDFLARE_ERROR"
NOT_FOUND_ERROR = "NOT_FOUND_ERROR"
FORBIDDEN_ERROR = "FORBIDDEN_ERROR"
CONTENT_ERROR = "CONTENT_ERROR"
REQUEST_ERROR = "REQUEST_ERROR"
NETWORK_ERROR = "NETWORK_ERROR"

RESPONSE_HTML = "HTML"
RESPONSE_JSON = "JSON"
RESPONSE_IMAGE = "IMAGE"

MARKER_CLOUDFLARE_CHALLENGE = 'id="trk_jschal_js"'
MARKER_PROXY_ERROR = "Proxy server error"

PROXY_TYPE_HTTP = "http"
PROXY_TYPE_TOR = "tor"
